# Values for Istio VirtualService used instead of Ingress
istio:
  enabled: false
  gateway: "istio-system/istio-gw"
  rpo:
    hostname: "rpo.esbproviders.example.com"

rpo:
  image:
    registry: harbor-infra.rfosp.local
    repository: rfosp/esbproviders/rpo
    tag: 'shotsnap'
    pullPolicy: IfNotPresent
